env:
  browser: false
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  no-console: 0
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
